version: '3.8'

services:
  findmypark-api:
    build:
      context: ./FindMyPark.API
      dockerfile: Dockerfile
    container_name: findmypark-api
    ports:
      - "5175:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    volumes:
      - ./data:/app/data # Persist SQLite DB
    restart: always

  findmypark-ui:
    build:
      context: ./FindMyPark.UI
      dockerfile: Dockerfile
    container_name: findmypark-ui
    ports:
      - "4200:80"
    depends_on:
      - findmypark-api
    restart: always
