version: '3.8'

services:
  findmypark-api:
    image: findmypark-api
    build:
      context: ./FindMyPark.API
      dockerfile: Dockerfile
    ports:
      - "5037:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=host.docker.internal)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=FREE)));User Id=system;Password=oracle;
    networks:
      - findmypark-network

  findmypark-ui:
    image: findmypark-ui
    build:
      context: ./FindMyPark.UI
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - findmypark-api
    networks:
      - findmypark-network

networks:
  findmypark-network:
    driver: bridge
